name: ssh-deploy

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build-and-deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{secrets.USERNAME}}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd deploy-test
          git clone https://github.com/chanwoong528/cicd-demo.git
          cd cicd-demo
          npm install
          npm run build
          pm2 serve dist/index.html 8080 --name "cicd-demo" --spa


  
    
